# Generated by Django 4.2.2 on 2023-06-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25, null='')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.categoria')),
            ],
        ),
    ]
