# Generated by Django 4.2.2 on 2023-06-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='data_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='titulo',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
